services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: tms_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  server:
    build: ./server
    environment:
      - PORT=5000
      - NODE_ENV=production
      - JWT_SECRET=super-secret-change-me
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=tms_db
      - DB_USER=root
      - DB_PASS=your_mysql_password
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mysql
    ports:
      - "5000:5000"
  client:
    build: ./client
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    ports:
      - "5173:80"

volumes:
  mysql_data:
